# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check out winrt-go fork
      uses: actions/checkout@v4
      with:
          repository: balazsgrill/winrt-go
          path: ../winrt-go

    - name: enable Projection FS
      run: Enable-WindowsOptionalFeature -Online -FeatureName Client-ProjFS -NoRestart
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Get tools
      run: |
        go install github.com/akavel/rsrc@latest 
        go install github.com/saltosystems/winrt-go/cmd/winrt-go-gen@latest

    - name: Test
      run: go test -v ./...
    
    - name: Generate
      run: go generate ./...
      
    - name: Build
      run: go build -o potatodrive.exe ./cmd/main
    - uses: actions/upload-artifact@v4
      with:
        name: potatodrive.exe
        path: potatodrive.exe
