# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Check out winrt-go fork
      uses: actions/checkout@v4
      with:
          repository: balazsgrill/winrt-go
          path: winrt-go

    - name: enable Projection FS
      run: Enable-WindowsOptionalFeature -Online -FeatureName Client-ProjFS -NoRestart
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Get tools
      run: |
        go install github.com/akavel/rsrc@latest 

    - name: Test
      run: go test -v ./...
    
    - name: Generate
      run: go generate ./...
      
    - name: Build
      run: go build -o potatodrive.exe -ldflags="-H windowsgui" ./cmd/main
    - uses: actions/upload-artifact@v4
      with:
        name: potatodrive.exe
        path: potatodrive.exe
      
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 5.x
    - name: Install wix
      run: dotnet tool install --global wix
    - name: Create installer
      run: wix PotatoDrive.wxs -o PotatoDrive.msi
    - uses: actions/upload-artifact@v4
      with:
        name: PotatoDrive.msi
        path: PotatoDrive.msi
