# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - name: Get release info
      id: release_info
      if: github.ref_type == 'tag'
      uses: revam/gh-action-get-tag-and-version@v1
      with:
        tag: ${{ github.ref }}
        prefix: v
        prefixRegex: "[vV]?"
    
    - id: set_version
      uses: marcdomain/set-variables@v1.2
      name: Set version
      with:
        variables: |
          VERSION: '${{ github.ref_type }}' == 'tag' ? "${{ steps.release_info.outputs.version }}" : "0.0.0.0"